// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateInputsEndpoint } from "./TemplateInputsEndpoint";

export interface AddTemplateEndpointRequest { name: string | null, description: string | null, body: string | null, template_inputs: Array<TemplateInputsEndpoint> | null, }