// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateInputsEndpoint } from "./TemplateInputsEndpoint";

export interface TemplateEndpointResponse { name: string, description: string, template_inputs: Array<TemplateInputsEndpoint>, }