// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TemplateInputsEndpoint { name: string | null, default_value: string | null, }