// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RegisterEndpointRequest { email: string | null, password: string | null, first_name: string | null, last_name: string | null, }