// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Roles } from "./Roles";

export interface RolesListResponse { roles: Array<Roles>, count: bigint, }