// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RolePermissions } from "./RolePermissions";

export interface UserEndpointResponse { email: string, first_name: string, last_name: string, bio: string | null, image: string | null, roles: Array<RolePermissions>, }