// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NotificationMessage { id: bigint, datetime: bigint, channel: string, subject: string, message: string, }