// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AddGroupEndpointRequest { group_name: string | null, admin_email: string | null, }