// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SendNotificationEndpointRequest { address: string | null, subject: string | null, message: string | null, }