// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserListEndpoint { id: bigint, email: string, first_name: string, last_name: string, bio: string | null, image: string | null, }