// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserListEndpoint } from "./UserListEndpoint";

export interface UserListEndpointResponse { users: Array<UserListEndpoint>, count: bigint, }